### ISSUE TITLE
multiServers

### ISSUE THREAD

**Issue by wpresident** [linuxserver/docker-librespeed#18]
How to use multiServers html?
I want to have a choice.

![image](https://user-images.githubusercontent.com/19406558/188205226-373647be-701f-4e61-93d2-ab851adf7c87.png)

![image](https://user-images.githubusercontent.com/19406558/188205319-6661f7ad-83f2-41be-9cce-16c6b5a30fdd.png)

**Comment by Suhyang** [comment]
spd10gmz is act. speed test server is http and my librespeed site to http. https site connect to test server set http not found.
![image](https://user-images.githubusercontent.com/4597253/210337510-c47811a7-3a82-4142-8314-fa7eb099f76a.png)
