### ISSUE TITLE
[FEAT] Add parameter "enable_id_obfuscation" to environment variables

### ISSUE THREAD

**Issue by DenDeXTeR51** [linuxserver/docker-librespeed#29]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Want to set parameter "enable_id_obfuscation" from _results/telemetry_settings.php_ via docker environment variables

### Reason for change

If I want to change this parameter in  _results/telemetry_settings.php_ I had to re-write  file _telemetry_settings.php_. It will be easier if this parameter can be set as all other parameters (DB_,IPINFO_APIKEY, etc) via env variables.

**Comment by aptalca** [comment]
It's already set: https://github.com/linuxserver/docker-librespeed/blob/master/root/etc/s6-overlay/s6-rc.d/init-librespeed-config/run#L43

**Comment by DenDeXTeR51** [comment]
But its hardcode to 'true'. I want to set 'false' via docker evironemnt variables.

**Comment by aptalca** [comment]
We honestly didn't think anyone would want it off.

You can customize the container via https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

**Comment by DenDeXTeR51** [comment]
For example I use this image in AWS Elastic Container Service, and to change this parameter I need to add custom scripts that will be mounted to container to change only 1 parameter on every start of container instance... I can rebuild container and stored it in my private repo (only because of 1 parameter) OR I need to generate whole _results/telemetry_settings.php_ thta will be mounted to _results/telemetry_settings.php_ mount file, and your script that set Vars inside it, is not needed anymore.
The best part of linuxserver/librespeed container that it has almost all parameters from _results/telemetry_settings.php_ already in Env Vars.. (except enable_id_obfuscation :( ) and people dont need to modify/rebuild and store custme images.

**Comment by drizuid** [comment]
We do not plan to add additional envvars, but you can customize as you see fit per aptalca's comment.
