### ISSUE TITLE
Enable customization of the image too

### ISSUE THREAD

**Issue by yurividal** [linuxserver/docker-librespeed#6]
Please enable the customizatin of the results image. The file that generates the image is located in `/usr/share/webapps/librespeed/results/index.php`
The same symlink strategy that was used with index.html could be used to allow changes to this file.

Furthermore, adding an /img directory to the /config would allow users to upload and use their custom logos and favicons.

**Comment by ironicbadger** [comment]
Hi @yurividal I just opened PR #7 which should make your request possible with this container.

**Comment by aptalca** [comment]
#7
